version: '2'

services:
  ombi:

    image: linuxserver/ombi
    container_name: ombi
    privileged: true
    restart: always
    ports:
      - 3579:3579

    volumes:
      - /opt/docker-ombi/config:/config

    environment:
      - TZ=Australia/Brisbane
