version: '2'

services:
  tvhproxy:

    image: jkaberg/tvhproxy
    container_name: tvhproxy
    privileged: true
    restart: always
    ports:
      - 5005:5004

    volumes:
      - /etc/localtime:/etc/localtime:ro

    environment:
      # Update to the IP of your tvHeadend Server...
      - TVH_URL=http://127.0.0.1:9981/
